// src/main/java/com/bsgated/model/DeliveryPass.java
package com.bsgated.model;

import jakarta.persistence.*;
import java.time.LocalDateTime;

@Entity
@Table(name = "delivery_passes")
public class DeliveryPass {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // Who created this pass
    @Column(nullable = false)
    private String hostResidentId;

    @Column(nullable = false)
    private String hostResidentName;

    @Column(nullable = false)
    private String hostUnit;

    // Delivery details
    @Column(nullable = false)
    private String provider; // Swiggy, Amazon, Zomato, etc.

    private String expectedWindow; // "Within 30 mins", "1-2 hours", etc.

    // Optional — resident may or may not know these
    private String deliveryPersonName;
    private String deliveryPersonPhone;

    // OTP — generated by backend, never by frontend
    @Column(nullable = false, length = 6)
    private String otp;

    // Status: PENDING → OTP_VERIFIED → DELIVERED | CANCELLED
    @Column(nullable = false)
    private String status = "PENDING";

    // Timestamps
    @Column(nullable = false)
    private LocalDateTime createdAt = LocalDateTime.now();

    private LocalDateTime otpVerifiedAt;
    private LocalDateTime deliveredAt;
    private LocalDateTime cancelledAt;

    // Guard who verified
    private String verifiedByGuardId;

    // Getters & Setters
    public Long getId() {
        return id;
    }

    public String getHostResidentId() {
        return hostResidentId;
    }

    public void setHostResidentId(String v) {
        this.hostResidentId = v;
    }

    public String getHostResidentName() {
        return hostResidentName;
    }

    public void setHostResidentName(String v) {
        this.hostResidentName = v;
    }

    public String getHostUnit() {
        return hostUnit;
    }

    public void setHostUnit(String v) {
        this.hostUnit = v;
    }

    public String getProvider() {
        return provider;
    }

    public void setProvider(String v) {
        this.provider = v;
    }

    public String getExpectedWindow() {
        return expectedWindow;
    }

    public void setExpectedWindow(String v) {
        this.expectedWindow = v;
    }

    public String getDeliveryPersonName() {
        return deliveryPersonName;
    }

    public void setDeliveryPersonName(String v) {
        this.deliveryPersonName = v;
    }

    public String getDeliveryPersonPhone() {
        return deliveryPersonPhone;
    }

    public void setDeliveryPersonPhone(String v) {
        this.deliveryPersonPhone = v;
    }

    public String getOtp() {
        return otp;
    }

    public void setOtp(String v) {
        this.otp = v;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String v) {
        this.status = v;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public LocalDateTime getOtpVerifiedAt() {
        return otpVerifiedAt;
    }

    public void setOtpVerifiedAt(LocalDateTime v) {
        this.otpVerifiedAt = v;
    }

    public LocalDateTime getDeliveredAt() {
        return deliveredAt;
    }

    public void setDeliveredAt(LocalDateTime v) {
        this.deliveredAt = v;
    }

    public LocalDateTime getCancelledAt() {
        return cancelledAt;
    }

    public void setCancelledAt(LocalDateTime v) {
        this.cancelledAt = v;
    }

    public String getVerifiedByGuardId() {
        return verifiedByGuardId;
    }

    public void setVerifiedByGuardId(String v) {
        this.verifiedByGuardId = v;
    }
}
